### ISSUE TITLE
Texto inicial do datapackage

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/dpckan#123]
Verificar função de replicar readme, como participar e contributting.

Completar o contributting para os que ainda não têm

**Comment by gabrielbdornas** [comment]
@fjuniorr implementamos a melhoria nesta visualização do CKAN. 

Sendo assim o fluxo final será:

Existindo arquivo README.md publicação considerará apenas as informações deste arquivo e não as existentes na propriedade description do arquivo datapackage.json

Não existindo o arquivo README.md a publicação considerará as informações existentes  na propriedade description do arquivo datapackage.json.

Obs.: Caso CONTRIBUTING.md e CHANGELOG.md existirem eles também serão considerados.

Para @Andrelamor deveríamos obrigar os usuários a criar o arquivo README.md como forma de deixar as informações do conjunto publicado no CKAN mais completas. Coloco aqui para discutirmos sobre
