### ISSUE TITLE
Erro na carga de data packages que não armazenam arquivos dos recursos em data/

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/dpckan#13]
- Versão dpkgckan: d68e7c9252dd9a6d90343e8a8b0bcea64c0d7385
- Data package: https://github.com/dados-mg/datapackage-reprex/tree/reprex1

Ao executar o código abaixo no console do Python inicializado na pasta `datapackage-reprex`

```python
import os
from dpkgckanmg.publish import publish
publish('.', os.environ['DADOSMG_DEV'])
```

Eu recebo o erro 

```
'Criacao de DataSet inicializada: .'
Traceback (most recent call last):
  File "/Users/fjunior/Local/cge/dados-mg/dpkgckanmg/dpkgckanmg/functions.py", line 288, in importaDataSet
    arquivosData = buscaArquivos(diretorio + separador + "data",separador,bool(False))
  File "/Users/fjunior/Local/cge/dados-mg/dpkgckanmg/dpkgckanmg/functions.py", line 62, in buscaArquivos
    os.listdir(diretorio)
FileNotFoundError: [Errno 2] No such file or directory: './data'
```

O erro está acontecendo porque os arquivos dos recursos estão sendo extraídos de forma fixa da pasta `data/`  ao invés de extraídos da propriedade `path` de cada recurso (que é o comportamento correto) no `datapackage.json`.

https://github.com/dados-mg/dpkgckanmg/blob/d68e7c9252dd9a6d90343e8a8b0bcea64c0d7385/dpkgckanmg/functions.py#L285-L288

Esse data package possui apenas um recurso na raiz da pasta mas é [válido](https://specs.frictionlessdata.io/data-package/#illustrative-structure) e deve ser carregado.

**Comment by gabrielbdornas** [comment]
fechado com o [PR](https://github.com/dados-mg/dpckan/pull/34)
