### ISSUE TITLE
`dpkcan dataset update` não atualiza datapackag.json com modificações

### ISSUE THREAD

**Issue by gabrielbdornas** [dados-mg/dpckan#136]
Durante testes realizados com @Andrelamor verificamos que modificações em metadados do conjunto de dados (datapackage.json) não são comparadas/atualizadas.

**Comment by gabrielbdornas** [comment]
@fjuniorr e @Andrelamor solicito que atualizem a versão do dpckan nos ambientes python dos seus projetos.

@Andrelamor esta versão corrige o problema de encoding que você estava enfrentando. Solicito que realize o teste para confirmarmos se está tudo certo.

**Comment by Andrelamor** [comment]
@gabrielbdornas [teste realizado e bem sucedido](https://homologa.cge.mg.gov.br/dataset/activity/violencia-contra-mulher), obrigado
