### ISSUE TITLE
2° ciclo de iteração pacote dpkgckanmg

### ISSUE THREAD

**Issue by gabrielbdornas** [dados-mg/dpckan#15]
Conforme [reunião de alinhamento](https://github.com/transparencia-mg/notas-reunioes/blob/master/notas/2021-05-19_DTI-DTA.md) realizado em 19/01/2021 

### Prazos

- Data Início: 20/05/2021
- Data Fim: 02/06/2021

### Responsáveis

- Desenvolvimento: Gabriel - DTA
- Revisão e merge: Maurício DTI

### Objetivos

Inclua aqui uma breve descrição do objetivo deste ciclo de desenvolvimento, podendo o formato de lista ser utilizado

- [x] Abertura do repositório
- [x] Itens restantes da primeira iteração
    - [x] Desenvolvimento de interface CLI para funcionalidades já desenvolvidas
    - [x] Publicar documentação utilizando github pages
- [x] feature
  - [x] inserir argumento para receber instância CKAN da publicação
    - [x] Função publish;
    - [x] Retirar ambiente padrão homologa (informed_environment='homologa') na função importaDataSet. Padronizar o default na chamada das funções e não nesta função
    - [x] Corrigir Issue #20 sobre erro ao tentar publicar em ambiente de produção
- [x] Colocar "separador" dentro de cada função, não sendo necessário passá-lo como parametro durante a chamada da função (utilizar os_forward_slash_publish = separador). 
    - [x] Função publish;

- [x] armazenamento único da versão
- [x] docs
  - [x]  escrita da documentação publish cli e web
- bugfix
  - [x] erro de publicação de conjuntos com múltiplos recursos
  - [x] retirar `time.sleep`
  - `createResource.py` não cria novos recursos, recebe argumentos incorretos e duplica `datapackage.json`
- [x] refactoring
- [x] renomear funcões (para inglês)
  - [x] padronizar ordem dos argumento
    - [x] Função publish;
    - [x] Função dataSet;
    - [x] Funçao resource; e
    - [x] Função criarArquivo2.
  
- design
  - [x] #37

### Histórico

Dar continuidade aos trabalhos de automatização das rotinas de publicação e manutenção de conjunto de dados no [Portal de Dados Abertos de Minas Gerais](https://dados.mg.gov.br/)

### Funcionalidades a serem desenvolvidas

- [x] Projeto Público
- [x] Documentação online, pública, utilizando-se de ferramentas gratúitas
- [x] Bug-fix/refatoração

**Comment by fjuniorr** [comment]
@gabrielbdornas faltou inserir no escopo dessa iteração a automatização do scan do repositório com o gitleaks para evitar vazamento acidental de chaves do CKAN.

Eu vejo duas opções (com preferência a primeira sem avaliar a complexidade)

- Configurar um pre-commit hook no git para execução local do gitleaks impedindo commits com segredos
- Configurar execução do gitleaks via integração continua com o github actions

Mesmo que a gente não faça isso nessa iteração, captura isso por favor.
