### ISSUE TITLE
Dificuldade para publicar documentação online utilizando github pages

### ISSUE THREAD

**Issue by gabrielbdornas** [dados-mg/dpckan#19]
Os primeiros testes para publicação da documentação online do projeto utilizando [github pages](https://pages.github.com/) não foi bem sucedida. Basicamente a documentação fica disponível, mas perde o estilo, muito similar ao relatado neste [stackoverflow post](https://stackoverflow.com/questions/62626125/github-pages-with-sphinx-generated-documentation-not-displaying-html-correctly).

Minha suspeita original, a partir do posto citado acima e deste [outro](https://github.com/sphinx-doc/sphinx/issues/3382) é dificuldade enfrentada pela ferramenta de ler "relative_permalinks", como também levantado na [própria documentação](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/troubleshooting-jekyll-build-errors-for-github-pages-sites)

>Relative permalinks configured
>This errors means that you have relative permalinks, which are not supported by GitHub Pages, in your _config.yml file.
>
>Permalinks are permanent URLs that reference a particular page on your site. Absolute permalinks begin with the root of the >site, while relative permalinks begin with the folder containing the referenced page. GitHub Pages and Jekyll no longer support >relative permalinks. For more information about permalinks, see "Permalinks" in the Jekyll documentation.
>
>To troubleshoot, remove the relative_permalinks line from your _config.yml file and reformat any relative permalinks in your site >with absolute permalinks. For more information, see "Editing files in your repository."

Realizar testes modificando as tags de estilo do arquivo index.html para referenciar os arquivos deste a raiz do projeto e não o caminho relativo ao próprio arquivo index.html

A publicação na ferramenta [ReadTheDocs](https://readthedocs.org/), funcionou perfeitamente. Sendo assim publicarei nela, tendo em vista que o objetivo principal é ter a documentação do projeto publicado online, não se importando qual a ferramenta deverá ser utilizada. Uma outra vantagem na utilização desta ferramenta é a facilidade de publicação, não sendo necessário modificar nada no código, exigências presentes na publicação via github pages.

Encaminhamentos para finaizar o issue:
- [x] Criar uma conta [ReadTheDocs](https://readthedocs.org/) para o email dadosabertos@cge.mg.gov.br
- [ ] Validar a conta criada a conta guithub/dados-mg para publicação da documentação (apresentando erro na primeira tentativa, conforme print abaixo:)
![Screenshot from 2021-06-02 16-06-59](https://user-images.githubusercontent.com/49699290/120538192-979f4e80-c3bc-11eb-80a2-e6e095fe0993.png)
- [ ] Publicar documentação online após merge do [PR 18](https://github.com/dados-mg/dpkgckanmg/pull/18)

@fjuniorr, em algum outro momento o e-mail dadosabertos@cge.mg.gov.br foi utilizado para criação de conta na [ReadTheDocs](https://readthedocs.org/)?

**Comment by fjuniorr** [comment]
> @fjuniorr, em algum outro momento o e-mail [dadosabertos@cge.mg.gov.br](mailto:dadosabertos@cge.mg.gov.br) foi utilizado para criação de conta na [ReadTheDocs](https://readthedocs.org/)?

Acho que não @gabrielbdornas.

Alguns emails foram pro caixa de spam dessa conta no dia 02/06. Marquei como não spam mas não cliquei no link de ativação (vou deixar vc fazer isso porque fica mais fácil testar se deu certo).

![Caixa_de_Entrada_•_dadosabertos_cge_mg_gov_br](https://user-images.githubusercontent.com/4969445/121033187-57581b80-c782-11eb-8c8b-f8942bfaff70.png)

**Comment by gabrielbdornas** [comment]
Documentação publicada [aqui](https://dpckan.readthedocs.io/en/latest/)
