### ISSUE TITLE
Regra para carga do datapackage.json no CKAN durante operações de criação e atualização

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/dpckan#33]
Na [especificação original](https://github.com/dados-mg/dpkgckan) do `dpckan` não havia a previsão de que os arquivos json armazenando os metadados do data package (eg. `datapackage.json`, `tableschema.json`, `dialect.json`) também deveriam ser carregados como recursos do CKAN.

No entanto, esse comportamento foi parcialmente implementado e atende uma demanda real de permitir acesso ao data package "completo" e em formato legível por máquina.

No comportamento atual todos os arquivos `json` estão sendo carregados.

O novo comportamento a ser implementado é que somente o arquivo `datapackage.json` deve ser carregado depois de todas as operações, com os metadados expandidos (vide https://github.com/dados-mg/dpckan/issues/7#issuecomment-870942788 para a melhor forma de fazer isso).

Essa decisão foi tomada pelo pragmatismo que ele é o único recurso em que o nome do arquivo serve para identificar o recurso.

**Comment by gabrielbdornas** [comment]
fechado com o [PR](https://github.com/dados-mg/dpckan/pull/34)
