### ISSUE TITLE
Erro "Não foi possível criar o dataset" com `dpckan publish`

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/dpckan#36]
Criei um data package bem completo para testes disponível em [data-types](https://github.com/dados-mg/datapackage-reprex/tree/data-types).

Tentando publicar com o código do commit 88277a1 recebi o erro abaixo:

```bash
$ dpckan publish
----Iniciando publicação/atualização datasest----
----Publicação/atualização datasest em https://homologa.cge.mg.gov.br----
----Iniciando verificações----
----Nome do dataset: data-types----
----Resources encontrado no arquivo datapackage.json----
----Host https://homologa.cge.mg.gov.br válido----
----Verificações realizadas com sucesso----
Não foi possível criar o dataset.
```

No fim das contas erros nunca são específicos demais.

**Comment by fjuniorr** [comment]
Nesse caso o erro estava acontecendo pois esse trecho da função `load_complete_json` 

https://github.com/dados-mg/dpckan/blob/4ef0cecad0d7df2dd37f30e53e5fc55806ec6dd2/dpckan/functions.py#L168-L170

assume a necessidade de uma propriedade `dialect` em todos os recursos que esteja documentada com um arquivo json externo. Ele gera erro nas seguintes situações:

- `KeyError: 'dialect'` recurso não tem propriedade `dialect` definido
- `FileNotFoundError: [Errno 2] No such file or directory: ';'`: recurso definiu a propriedade `dialect` no arquivo `datapackage.json`
- `json.decoder.JSONDecodeError`: recurso definiu a propriedade `dialect` em um arquivo `yaml` (não é válido pela spec mas vamos querer suportar esse caso de uso)

**Comment by gabrielbdornas** [comment]
@fjuniorr acredito que solucionamos esse issue no o [PR](https://github.com/dados-mg/dpckan/pull/34), ficando apenas a parte de tipos de dados pendentes. Que tal fecharmos esse issue e abrirmos um especificamente para este problema?
