### ISSUE TITLE
Erro durante carga do dicionário de dados de data packages que utilizam table schema em arquivo externo (schema.json)

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/dpckan#7]
Para reproduzir esse erro utilizar [esse](https://github.com/dados-mg/letters-datapackage/releases/tag/reprex7) conjunto de dados e o commit 0df48b376fa14138c84f5e8f11d801b598e73904. Você pode fazer isso na linha de comando com

```bash
git clone https://github.com/dados-mg/letters-datapackage.git
cd letters-datapackage
git checkout -b reprex reprex7 # cria um branch reprex igual a tag reprex7
# ative seu ambiente virtual
pip install -r requirements.txt 
```

No console do python ao executar

```python
import os # para extrair o valor da variavel de ambiente DADOSMG_DEV contendo a chave da API CKAN
from dpkgckanmg.publish import publish
publish('.', os.environ['DADOSMG_DEV'])
```

A carga funciona até a atualização do dicionário de dados

```python
'Criacao de DataSet inicializada: .'
'------------------------------------------------'
'Atualizacao de dicionario de dados inicializada: letters-vowels.csv'
Traceback (most recent call last):
  File "dpkgckanmg/dpkgckanmg/functions.py", line 383, in importaDataSet
    atualizaDicionario(caminhoCompletoJson,resource_id,name,authorization,separador)
  File "dpkgckanmg/dpkgckanmg/functions.py", line 515, in atualizaDicionario
    fieldsList = n['schema']['fields']
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dpkgckanmg/publish.py", line 49, in publish
    importaDataSet(authorizaton,"",caminho,"csv",privado,autor,type,tags,separador,"",comandoDelete,so)
  File "dpkgckanmg/functions.py", line 386, in importaDataSet
    print("Nao foi possivel atualizar o dicionario de dados. Erro: " + e)
TypeError: can only concatenate str (not "TypeError") to str
```

O erro está ocorrendo porque o `datapackage.json` está usando para o recurso `letters` uma [referência para um arquivo externo](https://github.com/dados-mg/letters-datapackage/blob/reprex7/datapackage.json#L46) `schema.json`.

Isso é válido pela [especificação](https://specs.frictionlessdata.io/tabular-data-resource/#introduction)

> The schema property MUST follow the Table Schema (opens new window)specification, either as a JSON object directly under the property, or a string referencing another JSON document containing the Table Schema

e é utilizado em produção no [conjunto da remuneração](https://github.com/dados-mg/remuneracao/blob/master/datapackage.json) para evitar a repetição desnecessária do schema (vide https://github.com/dados-mg/issues/issues/12 para histórico).

Também usamos um arquivo externo para a propriedade `dialect`, apesar de não ter encontrado isso na [especificação](https://specs.frictionlessdata.io/csv-dialect/#language).

**Comment by fjuniorr** [comment]
@gabrielbdornas esse erro ainda está ocorrendo e precisamos corrigir ele ainda nessa iteração. Podemos usar o `frictionless.py` para fazer a dereferenciação sem implantar essa lógica. Se a gente ler um data package com schema externo

```python
from frictionless import Package
from pprint import pprint

dp = Package('https://raw.githubusercontent.com/dados-mg/datapackage-reprex/foreign-key-constraint/datapackage.json')

pprint(dp.get_resource('pib-per-capita'))
```

A propriedade `schema` vai armazenar o caminho para o table schema.

```
{'encoding': 'utf-8',
 'format': 'csv',
 'name': 'pib-per-capita',
 'path': 'data/pib-per-capita.csv',
 'profile': 'tabular-data-resource',
 'schema': 'schema/pib-per-capita.json'} # path para table schema no lugar do table schema
```

Podemos usar o método `expand`

```python
dp.get_resource('pib-per-capita').dialect.expand()
dp.get_resource('pib-per-capita').schema.expand()

pprint(dp.get_resource('pib-per-capita'))
```

E aí os metadados estão disponíveis

```
{'dialect': {'delimiter': ',', # dialect default também expandido que nem existia no data package original
             'doubleQuote': True,
             'lineTerminator': '\r\n',
             'quoteChar': '"',
             'skipInitialSpace': False},
 'encoding': 'utf-8',
 'format': 'csv',
 'name': 'pib-per-capita',
 'path': 'data/pib-per-capita.csv',
 'profile': 'tabular-data-resource',
 'schema': {'fields': [{'bareNumber': True, # schema expandido
                        'format': 'default',
                        'name': 'COD',
                        'type': 'integer'},
                       {'bareNumber': True,
                        'decimalChar': ',',
                        'format': 'default',
                        'groupChar': '.',
                        'name': 'POP_2013',
                        'type': 'number'},
                       {'bareNumber': True,
                        'decimalChar': ',',
                        'format': 'default',
                        'groupChar': '.',
                        'name': 'PIB_2013',
                        'type': 'number'},
                       {'bareNumber': True,
                        'decimalChar': ',',
                        'format': 'default',
                        'groupChar': '.',
                        'name': 'PIB_PER_CAPITA_2013',
                        'type': 'number'}],
            'foreignKeys': [{'fields': 'COD',
                             'reference': {'fields': 'COD',
                                           'resource': 'estados'}}],
            'missingValues': [''],
            'primaryKey': 'COD'}}
```

Também é possível expandir o recurso inteiro de uma vez (ie. `dp.get_resource('pib-per-capita').expand()`) mas isso adiciona algumas propriedades extras no recurso que não fazem parte da especificação mas são usadas pelo `frictionless.py`


Ps. Achei o trecho relevante da [especificação](https://specs.frictionlessdata.io/implementation/#on-dereferencing-and-descriptor-validation)

> ### On dereferencing and descriptor validation
> 
> Some properties in the Frictionless Data specifications allow a path (a URL or a POSIX path) that resolves to an object.
> 
> The most prominent example of this is the `schema` property on Tabular Data Resource descriptors.
> 
> Allowing such references has practical use for publishers, for example in allowing schema reuse. However, it does introduce difficulties in the validation of such properties. For example, validating a path pointing to a schema rather than the schema object itself will do little to guarantee the integrity of the schema definition. Therefore implementors `MUST` dereference such "referential" property values before attempting to validate a descriptor. At present, this requirement applies to the following properties in Tabular Data Package and Tabular Data Resource:
> 
> - `schema`
> - `dialect`

**Comment by gabrielbdornas** [comment]
fechado com o [PR](https://github.com/dados-mg/dpckan/pull/34)
